#!/bin/bash
# DEVON-CODE.SH — Local LLM coder using Ollama (Qwen 3.5 35B)
# Zero Claude tokens. Runs entirely on local RTX A6000 GPUs.
# Devon writes code. Brett reviews it. They complement each other.
# Usage: ./devon-code.sh [brief_file] [target_file]
set -e

REPO="/home/tawfeeq/ramadan-clock-site"
CREW_DIR="$REPO/.crew"
BRIEF="${1:-$CREW_DIR/BRIEF.md}"
TARGET="${2:-}"
MODEL="qwen3.5:35b-a3b"
FINDINGS="$CREW_DIR/FINDINGS.md"

cd "$REPO"

SPEC=$(cat "$BRIEF" 2>/dev/null || echo "No brief found")

# Read existing target file for context if provided
EXISTING=""
if [ -n "$TARGET" ] && [ -f "$TARGET" ]; then
  LINES=$(wc -l < "$TARGET")
  if [ "$LINES" -gt 200 ]; then
    EXISTING=$(tail -200 "$TARGET")
    EXISTING="[File truncated — showing last 200 lines]\n${EXISTING}"
  else
    EXISTING=$(cat "$TARGET")
  fi
fi

# Read Brett's review if available (incorporate feedback)
BRETT_REVIEW=""
if [ -f "$CREW_DIR/REVIEW.md" ]; then
  BRETT_REVIEW=$(cat "$CREW_DIR/REVIEW.md")
fi

PROMPT="You are Devon, a senior full-stack developer. You write clean, precise, production-ready code.

Languages & expertise: JavaScript, TypeScript, Python, Bash, HTML, CSS, GLSL, SQL, JSON, YAML, Markdown, Three.js, WebGL, Node.js, React, bpy (Blender Python).

BRIEF (what to build):
${SPEC}

$([ -n "$EXISTING" ] && echo "EXISTING FILE CONTEXT (modify/extend this):
${EXISTING}")

$([ -n "$BRETT_REVIEW" ] && echo "BRETT'S PREVIOUS REVIEW (address these issues):
${BRETT_REVIEW}")

Rules:
- Output ONLY the complete file content, no explanations, no markdown fences
- Follow the brief exactly — every requirement must be met
- If modifying an existing file, output the FULL modified file
- Write production-quality code: no TODOs, no placeholders, no debug logs left in
- If the brief says HTML, output complete valid HTML
- If the brief says JS, output complete valid JS
- Be precise with values (positions, sizes, colors, timings)

Write the code now:"

echo "🔨 Devon coding (${MODEL})..."
echo "Brief: $BRIEF"
echo ""

TMPRESPONSE=$(mktemp /tmp/devon-response.XXXXXX)
TMPCODE=$(mktemp /tmp/devon-code.XXXXXX)

# Stream mode: write chunks as they arrive
curl -s http://localhost:11434/api/generate \
  -d "$(jq -n \
    --arg model "$MODEL" \
    --arg prompt "$PROMPT" \
    '{model: $model, prompt: $prompt, stream: true, options: {num_predict: 8000, temperature: 0.2}}' \
  )" \
  --max-time 600 > "$TMPRESPONSE" 2>&1

# Parse NDJSON stream: try jq first, fall back to python3
if jq -r '.response // ""' "$TMPRESPONSE" 2>/dev/null | tr -d '\n' > "$TMPCODE"; then
  # Check if jq actually produced output
  if [ ! -s "$TMPCODE" ]; then
    # jq returned empty — try python3 fallback
    python3 -c "import sys,json
for line in open('$TMPRESPONSE'):
    line=line.strip()
    if not line: continue
    try: sys.stdout.write(json.loads(line).get('response',''))
    except: pass" > "$TMPCODE" 2>/dev/null
  fi
else
  # jq failed entirely — python3 fallback
  python3 -c "import sys,json
for line in open('$TMPRESPONSE'):
    line=line.strip()
    if not line: continue
    try: sys.stdout.write(json.loads(line).get('response',''))
    except: pass" > "$TMPCODE" 2>/dev/null
fi

CODE=$(cat "$TMPCODE")
if [ -z "$CODE" ]; then
  CODE="ERROR: No response from model"
fi

# Extract duration/tokens from last NDJSON line (contains totals)
LAST_LINE=$(tail -1 "$TMPRESPONSE")
DURATION=$(echo "$LAST_LINE" | jq -r '(.total_duration // 0) / 1000000000 | . * 10 | floor / 10' 2>/dev/null || echo "0")
TOKENS=$(echo "$LAST_LINE" | jq -r '.eval_count // 0' 2>/dev/null || echo "0")

rm -f "$TMPRESPONSE" "$TMPCODE"

echo "Devon wrote ${TOKENS} tokens in ${DURATION}s"
echo ""

# Write to FINDINGS.md for transparency
cat > "$FINDINGS" << EOF
# Devon's Output
_Generated by Devon (${MODEL}) in ${DURATION}s, ${TOKENS} tokens_

## Brief
$(cat "$BRIEF")

## Code Written
\`\`\`
$(echo "$CODE" | head -100)
\`\`\`
[Full output written to target file]
EOF

# Write code to target file if specified
if [ -n "$TARGET" ]; then
  echo "$CODE" > "$TARGET"
  echo "✅ Code written to: $TARGET"
else
  # Print to stdout so orchestrator can redirect
  echo "$CODE"
fi
